global:
    scrape_interval: 15s
    evaluation_interval: 15s
    external_labels:
        monitor: 'tmp-app'

scrape_configs:
    -   job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
            -   targets: [ 'localhost:9090' ]
                labels:
                    env: local
                    region: us-east-1

    -   job_name: 'cadvisor'
        scrape_interval: 5s
        static_configs:
            -   targets: [ 'localhost:8090' ]

    -   job_name: 'node_exporter'
        scrape_interval: 5s
        static_configs:
            -   targets: [ 'localhost:9100' ]

    -   job_name: 'alertmanager'
        scrape_interval: 5s
        static_configs:
            -   targets: [ 'alertmanager:9093' ]

    -   job_name: 'db_exporter'
        scrape_interval: 5s
        static_configs:
            -   targets: [ 'localhost:9187' ]

    -   job_name: 'backend'
        metrics_path: '/api/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
            -   targets: [ 'localhost:8081' ]

rule_files:
    - "/etc/prometheus/alertmanager/rules.yml"

alerting:
    alertmanagers:
        - scheme: http
          static_configs:
              - targets:
                    - "alertmanager:9093"
